platform :ios, '10.0'

project 'MobileTokenSDK'

target 'MobileTokenSDK' do
  use_frameworks!
  
  # PRODUCTION SETTINGS
  # pod 'PowerAuth2', '~> 1.2.2'
  # DEVELOPMENT SETTINGS
  pod 'PowerAuth2', :git => 'https://github.com/wultra/powerauth-mobile-sdk.git', :branch => 'develop', :submodules => true
end

# Disable bitcode for iOS targets (also see chapter Disabling bitcode)
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.platform_name == :ios
      puts "Disabling bitcode for target  #{target.name}"
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end
end
