name: build

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  build:
    name: Building the SDK
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Building
        run: ./scripts/build.sh
