name: build

on:
  push:
    branches:
      - develop
      - master
      - releases/*
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set proper xcode version
        run: sh ./scripts/xcodeselect.sh
      - name: Building
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/build.sh