name: build

on:
  push:
    branches:
      - develop
      - master
      - release/*
  pull_request:
  schedule:
    - cron:  '25 6 * * *'

jobs:
  build:
    name: Build
    runs-on: macos-12
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Building
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/build.sh