name: build

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/build.sh
