name: tests

on:
  push:
    branches:
      - develop
      - master
      - releases/*
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: macos-13
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set proper xcode version
        run: sh ./scripts/xcodeselect.sh
      - name: Runing Tests
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SDK_CONFIG : ${{ secrets.TESTS_SDK_CONFIG }}
          CL_URL: ${{ secrets.TESTS_CL_URL }}
          CL_LGN: ${{ secrets.TESTS_CL_LGN }}
          CL_PWD: ${{ secrets.TESTS_CL_PWD }}
          CL_AID: ${{ secrets.TESTS_CL_AID }}
          OP_URL: ${{ secrets.TESTS_OP_URL }}
          ER_URL: ${{ secrets.TESTS_ER_URL }}
          IN_URL: ${{ secrets.TESTS_IN_URL }}
        run: ./scripts/test.sh -destination "platform=iOS Simulator,OS=17.0.1,name=iPhone 15" -sdkconfig "$SDK_CONFIG" -er "$ER_URL" -op "$OP_URL" -in "$IN_URL" -cl "$CL_URL" -clu "$CL_LGN" -clp "$CL_PWD" -cla "$CL_AID"