name: tests

on:
  push:
    branches:
      - develop
      - releases/*
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: macos-26
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set proper xcode version
        run: sh ./scripts/xcodeselect.sh
      - name: Runing Tests
        env:
          TESTS_CONFIG: ${{ secrets.TESTS_CONFIG }}
        run: ./scripts/test.sh -config "$TESTS_CONFIG"
