name: tests

on:
  push:
    branches:
      - develop
      - master
      - release/*
  pull_request:
  schedule:
    - cron:  '25 6 * * *'

jobs:
  tests:
    name: Tests
    runs-on: macos-11.0
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Runing Tests
        env:
          APP_KEY: ${{ secrets.TESTS_APP_KEY }}
          APP_SECRET: ${{ secrets.TESTS_APP_SECRET }}
          MASTER_SERVER_PUBLIC_KEY : ${{ secrets.TESTS_MASTER_SERVER_PUBLIC_KEY }}
          CL_URL: ${{ secrets.TESTS_CL_URL }}
          CL_LGN: ${{ secrets.TESTS_CL_LGN }}
          CL_PWD: ${{ secrets.TESTS_CL_PWD }}
          OP_URL: ${{ secrets.TESTS_OP_URL }}
          ER_URL: ${{ secrets.TESTS_ER_URL }}
        run: ./scripts/test.sh -destination "platform=iOS Simulator,OS=15.2,name=iPhone SE (2nd generation)" -appkey "$APP_KEY" -appsecret "$APP_SECRET" -masterspk "$MASTER_SERVER_PUBLIC_KEY" -er "$ER_URL" -op "$OP_URL" -cl "$CL_URL" -clu "$CL_LGN" -clp "$CL_PWD"